import os
import json
import uuid
from typing import Dict, Any, List
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


class ExportService:
    """
    Generates production downloadable files (.pptx, .pdf, .docx, .md) from completed task outputs.
    Saves compiled files to 'exports/' directory and returns accessible download URLs/paths.
    """

    EXPORTS_DIR = "exports"

    @classmethod
    def ensure_exports_dir(cls):
        if not os.path.exists(cls.EXPORTS_DIR):
            os.makedirs(cls.EXPORTS_DIR, exist_ok=True)

    @classmethod
    def compile_project_artifacts(
        cls,
        project_title: str,
        output_type: str,
        task_outputs: Dict[str, Any]
    ) -> List[Dict[str, str]]:
        """
        Compile project outputs into real files on disk.
        Returns list of artifact dicts: [{"name": filename, "path": relative_path, "type": file_type}]
        """
        cls.ensure_exports_dir()
        artifacts = []
        uid = str(uuid.uuid4())[:8]
        safe_title = "".join(c if c.isalnum() else "_" for c in project_title[:30])

        if output_type == "presentation":
            # Build PPTX Presentation
            pptx_filename = f"{safe_title}_{uid}.pptx"
            pptx_path = os.path.join(cls.EXPORTS_DIR, pptx_filename)
            cls.generate_pptx(project_title, task_outputs, pptx_path)
            artifacts.append({
                "name": f"{project_title}.pptx",
                "filename": pptx_filename,
                "url": f"/exports/{pptx_filename}",
                "type": "PowerPoint Presentation (.pptx)"
            })

        # Also generate PDF document report for documents or presentations
        pdf_filename = f"{safe_title}_{uid}.pdf"
        pdf_path = os.path.join(cls.EXPORTS_DIR, pdf_filename)
        cls.generate_pdf(project_title, task_outputs, pdf_path)
        artifacts.append({
            "name": f"{project_title}.pdf",
            "filename": pdf_filename,
            "url": f"/exports/{pdf_filename}",
            "type": "PDF Report (.pdf)"
        })

        # Markdown report artifact
        md_filename = f"{safe_title}_{uid}.md"
        md_path = os.path.join(cls.EXPORTS_DIR, md_filename)
        cls.generate_markdown(project_title, task_outputs, md_path)
        artifacts.append({
            "name": f"{project_title}.md",
            "filename": md_filename,
            "url": f"/exports/{md_filename}",
            "type": "Markdown Summary (.md)"
        })

        return artifacts

    @classmethod
    def generate_pptx(cls, title: str, task_outputs: Dict[str, Any], output_path: str):
        """Build native PowerPoint deck with python-pptx."""
        prs = Presentation()

        # Title Slide
        blank_slide_layout = prs.slide_layouts[6]
        slide = prs.slides.add_slide(blank_slide_layout)

        # Add background / Title Box
        txBox = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(8), Inches(2))
        tf = txBox.text_frame
        p = tf.paragraphs[0]
        p.text = title
        p.font.size = Pt(40)
        p.font.bold = True
        p.font.color.rgb = RGBColor(30, 41, 59)

        p2 = tf.add_paragraph()
        p2.text = "Generated by LiteMind AI Orchestrator"
        p2.font.size = Pt(18)
        p2.font.color.rgb = RGBColor(99, 102, 241)

        # Extract structured content from tasks
        slides_data = []
        for task_id, out in task_outputs.items():
            if isinstance(out, dict):
                if "slides" in out and isinstance(out["slides"], list):
                    slides_data.extend(out["slides"])
                elif "text" in out:
                    # Parse slides if text returned
                    slides_data.append({
                        "title": f"Section Analysis",
                        "points": [out["text"][:200] + "..."]
                    })

        if not slides_data:
            slides_data = [
                {"title": "Introduction & Key Concepts", "points": ["Overview of topic and foundational principles.", "Key facts and research findings.", "Core implications."]},
                {"title": "Detailed Findings & Analysis", "points": ["Structured evaluation of evidence.", "Key data metrics and parameters.", "Strategic takeaways."]},
                {"title": "Conclusion & Recommendations", "points": ["Summary of primary insights.", "Action items and next steps."]}
            ]

        # Add Content Slides
        for s_info in slides_data[:10]:
            slide = prs.slides.add_slide(prs.slide_layouts[1]) # Bullet slide layout
            slide.shapes.title.text = s_info.get("title", "Topic Overview")
            tf = slide.placeholders[1].text_frame
            points = s_info.get("points", s_info.get("bullet_points", []))
            if isinstance(points, list):
                for idx, pt in enumerate(points):
                    if idx == 0:
                        p = tf.paragraphs[0]
                    else:
                        p = tf.add_paragraph()
                    p.text = str(pt)
                    p.font.size = Pt(16)
            elif isinstance(points, str):
                tf.paragraphs[0].text = points

        prs.save(output_path)

    @classmethod
    def generate_pdf(cls, title: str, task_outputs: Dict[str, Any], output_path: str):
        """Build PDF Report with ReportLab."""
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            leading=28,
            textColor=colors.HexColor('#1E293B'),
            spaceAfter=15
        )

        h2_style = ParagraphStyle(
            'H2Style',
            parent=styles['Heading2'],
            fontSize=16,
            leading=20,
            textColor=colors.HexColor('#4F46E5'),
            spaceBefore=15,
            spaceAfter=10
        )

        body_style = ParagraphStyle(
            'BodyStyle',
            parent=styles['Normal'],
            fontSize=11,
            leading=16,
            textColor=colors.HexColor('#334155'),
            spaceAfter=10
        )

        story = []
        story.append(Paragraph(f"<b>{title}</b>", title_style))
        story.append(Paragraph("<i>Prepared by LiteMind Multi-AI Orchestrator Engine</i>", body_style))
        story.append(Spacer(1, 15))

        for task_id, out in task_outputs.items():
            if isinstance(out, dict):
                if "query" in out and "summary" in out:
                    story.append(Paragraph("Research Summary", h2_style))
                    story.append(Paragraph(out["summary"].replace("\n", "<br/>"), body_style))
                elif "text" in out:
                    story.append(Paragraph("Task Output Analysis", h2_style))
                    story.append(Paragraph(out["text"].replace("\n", "<br/>"), body_style))
                elif "slides" in out:
                    story.append(Paragraph("Slide Outline & Structure", h2_style))
                    for slide in out["slides"]:
                        story.append(Paragraph(f"<b>{slide.get('title', 'Slide')}</b>", body_style))
                        for pt in slide.get("points", []):
                            story.append(Paragraph(f"• {pt}", body_style))

        if len(story) <= 3:
            story.append(Paragraph("Executive Overview", h2_style))
            story.append(Paragraph("This document compiles key insights and analysis synthesized from LiteMind AI tools.", body_style))

        doc.build(story)

    @classmethod
    def generate_markdown(cls, title: str, task_outputs: Dict[str, Any], output_path: str):
        """Generate Markdown file."""
        lines = [f"# {title}\n", "*Generated by LiteMind AI Orchestration Platform*\n", "---\n"]

        for task_id, out in task_outputs.items():
            lines.append(f"## Task Execution [{task_id}]\n")
            if isinstance(out, dict):
                lines.append(f"```json\n{json.dumps(out, indent=2)}\n```\n")
            else:
                lines.append(f"{out}\n")

        with open(output_path, "w", encoding="utf-8") as f:
            f.writelines(lines)
