import os
import json
import uuid
from typing import Dict, Any, List
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from PIL import Image, ImageDraw, ImageFont


class ExportService:
    """
    Generates production downloadable files (.pptx, .pdf, .docx, .md) from completed task outputs.
    Saves compiled files to 'exports/' directory and returns accessible download URLs/paths.
    """

    EXPORTS_DIR = "exports"

    @classmethod
    def ensure_exports_dir(cls):
        if not os.path.exists(cls.EXPORTS_DIR):
            os.makedirs(cls.EXPORTS_DIR, exist_ok=True)

    @classmethod
    def compile_project_artifacts(
        cls,
        project_title: str,
        output_type: str,
        task_outputs: Dict[str, Any]
    ) -> List[Dict[str, str]]:
        """
        Compile project outputs into real files on disk.
        Returns list of artifact dicts: [{"name": filename, "path": relative_path, "type": file_type}]
        """
        cls.ensure_exports_dir()
        artifacts = []
        uid = str(uuid.uuid4())[:8]
        safe_title = "".join(c if c.isalnum() else "_" for c in project_title[:30])

        if output_type == "comic":
            # Build 2-width x 4-long (8 panel) Color Comic Grid Image
            comic_filename = f"{safe_title}_{uid}_comic.png"
            comic_path = os.path.join(cls.EXPORTS_DIR, comic_filename)
            cls.generate_comic_grid(project_title, task_outputs, comic_path)
            artifacts.append({
                "name": f"{project_title}_Comic_Strip.png",
                "filename": comic_filename,
                "url": f"/exports/{comic_filename}",
                "type": "Color Comic Strip Image (.png)"
            })

        if output_type == "presentation":
            # Build PPTX Presentation
            pptx_filename = f"{safe_title}_{uid}.pptx"
            pptx_path = os.path.join(cls.EXPORTS_DIR, pptx_filename)
            cls.generate_pptx(project_title, task_outputs, pptx_path)
            artifacts.append({
                "name": f"{project_title}.pptx",
                "filename": pptx_filename,
                "url": f"/exports/{pptx_filename}",
                "type": "PowerPoint Presentation (.pptx)"
            })

        # Also generate PDF document report for documents, comic, or presentations
        pdf_filename = f"{safe_title}_{uid}.pdf"
        pdf_path = os.path.join(cls.EXPORTS_DIR, pdf_filename)
        cls.generate_pdf(project_title, task_outputs, pdf_path)
        artifacts.append({
            "name": f"{project_title}.pdf",
            "filename": pdf_filename,
            "url": f"/exports/{pdf_filename}",
            "type": "PDF Report (.pdf)"
        })

        # Markdown report artifact
        md_filename = f"{safe_title}_{uid}.md"
        md_path = os.path.join(cls.EXPORTS_DIR, md_filename)
        cls.generate_markdown(project_title, task_outputs, md_path)
        artifacts.append({
            "name": f"{project_title}.md",
            "filename": md_filename,
            "url": f"/exports/{md_filename}",
            "type": "Markdown Summary (.md)"
        })

        return artifacts

    @classmethod
    def generate_pptx(cls, title: str, task_outputs: Dict[str, Any], output_path: str):
        """Build native PowerPoint deck with python-pptx."""
        prs = Presentation()

        # Title Slide
        blank_slide_layout = prs.slide_layouts[6]
        slide = prs.slides.add_slide(blank_slide_layout)

        # Add background / Title Box
        txBox = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(8), Inches(2))
        tf = txBox.text_frame
        p = tf.paragraphs[0]
        p.text = title
        p.font.size = Pt(40)
        p.font.bold = True
        p.font.color.rgb = RGBColor(30, 41, 59)

        p2 = tf.add_paragraph()
        p2.text = "Generated by LiteMind AI Orchestrator"
        p2.font.size = Pt(18)
        p2.font.color.rgb = RGBColor(99, 102, 241)

        # Extract structured content from tasks
        slides_data = []
        for task_id, out in task_outputs.items():
            if isinstance(out, dict):
                if "slides" in out and isinstance(out["slides"], list):
                    slides_data.extend(out["slides"])
                elif "text" in out:
                    # Parse slides if text returned
                    slides_data.append({
                        "title": f"Section Analysis",
                        "points": [out["text"][:200] + "..."]
                    })

        if not slides_data:
            slides_data = [
                {"title": "Introduction & Key Concepts", "points": ["Overview of topic and foundational principles.", "Key facts and research findings.", "Core implications."]},
                {"title": "Detailed Findings & Analysis", "points": ["Structured evaluation of evidence.", "Key data metrics and parameters.", "Strategic takeaways."]},
                {"title": "Conclusion & Recommendations", "points": ["Summary of primary insights.", "Action items and next steps."]}
            ]

        # Add Content Slides
        for s_info in slides_data[:10]:
            slide = prs.slides.add_slide(prs.slide_layouts[1]) # Bullet slide layout
            slide.shapes.title.text = s_info.get("title", "Topic Overview")
            tf = slide.placeholders[1].text_frame
            points = s_info.get("points", s_info.get("bullet_points", []))
            if isinstance(points, list):
                for idx, pt in enumerate(points):
                    if idx == 0:
                        p = tf.paragraphs[0]
                    else:
                        p = tf.add_paragraph()
                    p.text = str(pt)
                    p.font.size = Pt(16)
            elif isinstance(points, str):
                tf.paragraphs[0].text = points

        prs.save(output_path)

    @classmethod
    def generate_pdf(cls, title: str, task_outputs: Dict[str, Any], output_path: str):
        """Build PDF Report with ReportLab."""
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            leading=28,
            textColor=colors.HexColor('#1E293B'),
            spaceAfter=15
        )

        h2_style = ParagraphStyle(
            'H2Style',
            parent=styles['Heading2'],
            fontSize=16,
            leading=20,
            textColor=colors.HexColor('#4F46E5'),
            spaceBefore=15,
            spaceAfter=10
        )

        body_style = ParagraphStyle(
            'BodyStyle',
            parent=styles['Normal'],
            fontSize=11,
            leading=16,
            textColor=colors.HexColor('#334155'),
            spaceAfter=10
        )

        story = []
        story.append(Paragraph(f"<b>{title}</b>", title_style))
        story.append(Paragraph("<i>Prepared by LiteMind Multi-AI Orchestrator Engine</i>", body_style))
        story.append(Spacer(1, 15))

        for task_id, out in task_outputs.items():
            if isinstance(out, dict):
                if "query" in out and "summary" in out:
                    story.append(Paragraph("Research Summary", h2_style))
                    story.append(Paragraph(out["summary"].replace("\n", "<br/>"), body_style))
                elif "text" in out:
                    story.append(Paragraph("Task Output Analysis", h2_style))
                    story.append(Paragraph(out["text"].replace("\n", "<br/>"), body_style))
                elif "slides" in out:
                    story.append(Paragraph("Slide Outline & Structure", h2_style))
                    for slide in out["slides"]:
                        story.append(Paragraph(f"<b>{slide.get('title', 'Slide')}</b>", body_style))
                        for pt in slide.get("points", []):
                            story.append(Paragraph(f"• {pt}", body_style))

        if len(story) <= 3:
            story.append(Paragraph("Executive Overview", h2_style))
            story.append(Paragraph("This document compiles key insights and analysis synthesized from LiteMind AI tools.", body_style))

        doc.build(story)

    @classmethod
    def generate_markdown(cls, title: str, task_outputs: Dict[str, Any], output_path: str):
        """Generate Markdown file."""
        lines = [f"# {title}\n", "*Generated by LiteMind AI Orchestration Platform*\n", "---\n"]

        for task_id, out in task_outputs.items():
            lines.append(f"## Task Execution [{task_id}]\n")
            if isinstance(out, dict):
                lines.append(f"```json\n{json.dumps(out, indent=2)}\n```\n")
            else:
                lines.append(f"{out}\n")

        with open(output_path, "w", encoding="utf-8") as f:
            f.writelines(lines)

    @classmethod
    def generate_comic_grid(cls, title: str, task_outputs: Dict[str, Any], output_path: str):
        """
        Generate a 4-long x 2-width (2 columns x 4 rows = 8 panels total) color comic strip grid.
        Includes artwork backgrounds, panel frames, speech bubbles, captions, and panel headers.
        """
        # Extract panels from task outputs if available
        extracted_panels = []
        for task_id, out in task_outputs.items():
            if isinstance(out, dict) and "panels" in out and isinstance(out["panels"], list):
                extracted_panels = out["panels"]
                break

        # Fallback to 8 default panels if needed
        if len(extracted_panels) < 8:
            extracted_panels = [
                {
                    "panel_number": i + 1,
                    "title": f"Panel {i+1}: Chapter {i+1}",
                    "visual_prompt": f"Action comic scene for {title}",
                    "caption": f"Step {i+1} in the adventure of {title[:30]}...",
                    "dialogue": f"Character: Onward to step {i+1}!"
                }
                for i in range(8)
            ]

        # Image Dimensions: 1200px wide, 1800px high (2 cols x 4 rows)
        img_w, img_h = 1200, 1800
        img = Image.new("RGB", (img_w, img_h), "#0F172A") # Dark slate background
        draw = ImageDraw.Draw(img)

        # Header Title Banner
        draw.rectangle([20, 20, img_w - 20, 110], fill="#4F46E5", outline="#818CF8", width=4)
        draw.text((35, 35), f"COLOR COMIC: {title.upper()[:45]}", fill="#FFFFFF")
        draw.text((35, 75), "GRID FORMAT: 2-WIDTH x 4-LONG (8 PANELS) • GENERATED BY LITEMIND AI", fill="#C084FC")

        # Grid Coordinates: 2 columns, 4 rows
        col_w = 550
        row_h = 380
        padding_x = 30
        padding_y = 130
        gap_x = 40
        gap_y = 30

        panel_bg_colors = [
            ("#38BDF8", "#0284C7"), # Sky Blue
            ("#F472B6", "#DB2777"), # Vibrant Pink
            ("#34D399", "#059669"), # Mint Green
            ("#FBBF24", "#D97706"), # Amber Gold
            ("#A78BFA", "#7C3AED"), # Purple
            ("#FB923C", "#EA580C"), # Orange
            ("#2DD4BF", "#0D9488"), # Teal
            ("#F43F5E", "#E11D48")  # Coral
        ]

        for idx in range(8):
            row = idx // 2
            col = idx % 2

            x1 = padding_x + col * (col_w + gap_x)
            y1 = padding_y + row * (row_h + gap_y)
            x2 = x1 + col_w
            y2 = y1 + row_h

            panel_info = extracted_panels[idx] if idx < len(extracted_panels) else extracted_panels[0]
            bg_light, bg_dark = panel_bg_colors[idx % len(panel_bg_colors)]

            # Outer panel black border & colored background
            draw.rectangle([x1, y1, x2, y2], fill=bg_light, outline="#000000", width=6)

            # Internal comic artwork styling (decorative shapes/visuals)
            draw.ellipse([x1 + 30, y1 + 50, x1 + 250, y1 + 270], fill=bg_dark, outline="#FFFFFF", width=2)
            draw.polygon([(x2 - 180, y1 + 40), (x2 - 40, y1 + 180), (x2 - 120, y1 + 220)], fill="#FEF08A")

            # Panel Title Box (top left of panel)
            p_title = panel_info.get("title", f"Panel {idx+1}")
            draw.rectangle([x1 + 10, y1 + 10, x1 + 320, y1 + 45], fill="#0F172A", outline="#FFFFFF", width=2)
            draw.text((x1 + 20, y1 + 20), p_title[:32], fill="#F8FAFC")

            # Speech / Dialogue Bubble (Upper / Center right)
            dialogue = panel_info.get("dialogue", "Hero: Action!")
            if dialogue:
                bubble_x1, bubble_y1 = x1 + 160, y1 + 75
                bubble_x2, bubble_y2 = x2 - 20, y1 + 165
                draw.rectangle([bubble_x1, bubble_y1, bubble_x2, bubble_y2], fill="#FFFFFF", outline="#000000", width=3)
                # Speech tail
                draw.polygon([(bubble_x1 + 30, bubble_y2), (bubble_x1 + 15, bubble_y2 + 20), (bubble_x1 + 50, bubble_y2)], fill="#FFFFFF", outline="#000000")

                # Format dialogue text
                lines = [dialogue[i:i+35] for i in range(0, len(dialogue), 35)]
                for line_idx, line in enumerate(lines[:3]):
                    draw.text((bubble_x1 + 12, bubble_y1 + 12 + line_idx * 24), line, fill="#0F172A")

            # Caption Banner (Bottom of panel)
            caption = panel_info.get("caption", panel_info.get("visual_prompt", "Comic scene illustration"))
            cap_x1, cap_y1 = x1 + 10, y2 - 90
            cap_x2, cap_y2 = x2 - 10, y2 - 10
            draw.rectangle([cap_x1, cap_y1, cap_x2, cap_y2], fill="#FEF08A", outline="#000000", width=3)

            cap_lines = [caption[i:i+50] for i in range(0, len(caption), 50)]
            for cap_idx, cap_line in enumerate(cap_lines[:3]):
                draw.text((cap_x1 + 10, cap_y1 + 8 + cap_idx * 22), cap_line, fill="#1E293B")

        # Save composite comic strip image
        img.save(output_path, "PNG")
