import os
import time
import json
from typing import Dict, Any, Optional, List
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from docx import Document as DocxDocument
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from backend.adapters.base import BaseAdapter

OUTPUT_DIR = os.getenv("OUTPUT_DIR", "generated_outputs")
os.makedirs(OUTPUT_DIR, exist_ok=True)


class DocumentAdapter(BaseAdapter):
    """Document Generation Adapter for PPTX, PDF, and DOCX files."""

    def __init__(self, api_key: Optional[str] = None, config: Optional[Dict[str, Any]] = None):
        super().__init__(api_key=api_key, config=config)

    def authenticate(self) -> bool:
        return True

    def validate_input(self, input_data: Dict[str, Any]) -> bool:
        doc_type = input_data.get("format") or input_data.get("document_type")
        content = input_data.get("content") or input_data.get("slides") or input_data.get("sections")
        return bool(doc_type in ["pptx", "pdf", "docx"] and content)

    def estimate_cost(self, input_data: Dict[str, Any]) -> float:
        return 0.0

    def estimate_time(self, input_data: Dict[str, Any]) -> int:
        return 1500

    def validate_output(self, output_data: Dict[str, Any]) -> bool:
        return bool(output_data and output_data.get("file_path"))

    def execute(self, task_type: str, input_data: Dict[str, Any]) -> Dict[str, Any]:
        if not self.validate_input(input_data):
            return {
                "success": False,
                "output": None,
                "execution_time_ms": 0,
                "estimated_cost": 0.0,
                "error": "Invalid document generation input."
            }

        doc_type = (input_data.get("format") or input_data.get("document_type")).lower()
        title = input_data.get("title", "Generated_Document")
        timestamp = int(time.time())

        start_time = time.time()

        try:
            if doc_type == "pptx":
                file_path = self._generate_pptx(title, input_data, timestamp)
            elif doc_type == "pdf":
                file_path = self._generate_pdf(title, input_data, timestamp)
            elif doc_type == "docx":
                file_path = self._generate_docx(title, input_data, timestamp)
            else:
                return {
                    "success": False,
                    "output": None,
                    "execution_time_ms": 0,
                    "estimated_cost": 0.0,
                    "error": f"Unsupported format {doc_type}"
                }

            elapsed_ms = int((time.time() - start_time) * 1000)

            return {
                "success": True,
                "output": {
                    "content": f"Successfully generated {doc_type.upper()} file at {file_path}",
                    "file_path": file_path,
                    "format": doc_type,
                    "title": title
                },
                "execution_time_ms": elapsed_ms,
                "estimated_cost": 0.0,
                "error": None
            }

        except Exception as e:
            return {
                "success": False,
                "output": None,
                "execution_time_ms": int((time.time() - start_time) * 1000),
                "estimated_cost": 0.0,
                "error": f"Document generation failed: {str(e)}"
            }

    def _generate_pptx(self, title: str, input_data: Dict[str, Any], timestamp: int) -> str:
        prs = Presentation()
        # Set 16:9 aspect ratio
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = input_data.get("subtitle", "Generated by LiteMind AI Orchestration Platform")

        slides_data = input_data.get("slides") or []
        if not slides_data and isinstance(input_data.get("content"), list):
            slides_data = input_data["content"]
        elif not slides_data and isinstance(input_data.get("content"), str):
            # Parse text into slides by bullet points or headings
            raw_text = input_data["content"]
            sections = raw_text.split("\n\n")
            slides_data = [{"title": f"Section {i+1}", "bullets": [s.strip() for s in sec.split("\n") if s.strip()]} for i, sec in enumerate(sections)]

        bullet_slide_layout = prs.slide_layouts[1]
        for s_info in slides_data:
            s_title = s_info.get("title", "Slide")
            s_bullets = s_info.get("bullets") or s_info.get("points") or [s_info.get("content", "")]

            slide = prs.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = s_title

            tf = slide.placeholders[1].text_frame
            tf.word_wrap = True
            for idx, bullet in enumerate(s_bullets):
                if not bullet:
                    continue
                p = tf.add_paragraph() if idx > 0 else tf.paragraphs[0]
                p.text = str(bullet)
                p.level = 0

        filename = f"{title.replace(' ', '_')}_{timestamp}.pptx"
        full_path = os.path.join(OUTPUT_DIR, filename)
        prs.save(full_path)
        return full_path

    def _generate_pdf(self, title: str, input_data: Dict[str, Any], timestamp: int) -> str:
        filename = f"{title.replace(' ', '_')}_{timestamp}.pdf"
        full_path = os.path.join(OUTPUT_DIR, filename)

        doc = SimpleDocTemplate(full_path, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Title
        story.append(Paragraph(f"<b>{title}</b>", styles['Title']))
        story.append(Spacer(1, 12))

        content = input_data.get("content")
        if isinstance(content, str):
            paragraphs = content.split("\n")
            for p in paragraphs:
                if p.strip():
                    story.append(Paragraph(p.strip(), styles['Normal']))
                    story.append(Spacer(1, 8))
        elif isinstance(content, list):
            for item in content:
                if isinstance(item, dict):
                    story.append(Paragraph(f"<b>{item.get('title', '')}</b>", styles['Heading2']))
                    story.append(Spacer(1, 6))
                    body = item.get("content") or item.get("text", "")
                    story.append(Paragraph(str(body), styles['Normal']))
                    story.append(Spacer(1, 8))

        doc.build(story)
        return full_path

    def _generate_docx(self, title: str, input_data: Dict[str, Any], timestamp: int) -> str:
        doc = DocxDocument()
        doc.add_heading(title, level=0)

        content = input_data.get("content")
        if isinstance(content, str):
            doc.add_paragraph(content)
        elif isinstance(content, list):
            for section in content:
                if isinstance(section, dict):
                    doc.add_heading(section.get("title", ""), level=1)
                    doc.add_paragraph(section.get("content", ""))
                else:
                    doc.add_paragraph(str(section))

        filename = f"{title.replace(' ', '_')}_{timestamp}.docx"
        full_path = os.path.join(OUTPUT_DIR, filename)
        doc.save(full_path)
        return full_path
